version: '2'
services:
  product:
    image: hystrix-demo
    ports:
      - "8080"

  detail:
    image: hystrix-demo
    ports:
      - "8080"

  review:
    image: hystrix-demo
    ports:
      - "8080"

  ui:
    image: hystrix-demo
    ports:
      - "8080:8080"
    environment:
      PRODUCT_URL: http://product:8080
      DETAIL_URL: http://detail:8080
      REVIEW_URL: http://review:8080
